import { api } from '../api-client.js';
import { mountView } from '../components/view-shell.js';
import { createGrid } from '../components/data-grid.js';
import { showForm } from '../components/edit-form.js';
import { showSecretOnce } from '../components/secret-dialog.js';
import { confirmAction } from '../components/confirm-dialog.js';
import { notify } from '../components/notification.js';
import { serviceName, required } from '../utils/validation.js';
import { formatDate, statusHTML } from '../utils/formatting.js';
import { choice, optionalISOString, selectedValue, selectedValues } from '../utils/form-values.js';
import { permissionChoice, friendlyPermissionName } from '../utils/permissions.js';
import { createPermissionRule } from '../components/permission-form.js';

export async function render() {
  let consumersGrid; let keysGrid; let permissionsGrid; let selectedConsumer; let selectedKey; let selectedPermission;
  const shell = mountView('Consumers & keys', 'Manage client identities, access, and one-time credentials.', [{ label: 'New consumer', primary: true, onClick: createConsumer }, { label: 'Add access rule', onClick: async () => { if (await createPermissionRule()) await load(); } }], 'consumers');
  shell.content.innerHTML = '<div class="split-layout"><section class="panel"><h2>API clients</h2><div class="view-actions"><button id="edit-consumer" type="button" disabled>Edit</button><button id="remove-consumer" type="button" class="danger-button" disabled>Remove</button></div><div id="consumers-grid" class="grid-host"></div></section><div class="stack"><section class="panel"><h2>API keys</h2><p class="field-help">Clients send the issued key on protected requests as <code>X-API-Key: &lt;issued-api-key&gt;</code>.</p><div class="view-actions"><button id="issue-key" type="button" disabled>Create key</button><button id="rotate-key" type="button" disabled>Rotate</button><button id="revoke-key" type="button" class="danger-button" disabled>Revoke</button></div><div id="keys-grid" class="grid-host compact"></div></section><section class="panel"><h2>Access rules</h2><div class="view-actions"><button id="edit-permission" type="button" disabled>Edit notes</button><button id="remove-permission" type="button" class="danger-button" disabled>Remove</button></div><div id="permissions-grid" class="grid-host compact"></div></section></div></div>';
  const buttons = Object.fromEntries(['edit-consumer', 'remove-consumer', 'issue-key', 'rotate-key', 'revoke-key', 'edit-permission', 'remove-permission'].map((id) => [id, document.querySelector(`#${id}`)]));
  buttons['edit-consumer'].addEventListener('click', editConsumer); buttons['remove-consumer'].addEventListener('click', removeConsumer); buttons['issue-key'].addEventListener('click', issueKey); buttons['rotate-key'].addEventListener('click', rotateKey); buttons['revoke-key'].addEventListener('click', revokeKey); buttons['edit-permission'].addEventListener('click', editPermission); buttons['remove-permission'].addEventListener('click', removePermission);
  function refreshButtons() { buttons['edit-consumer'].disabled = !selectedConsumer; buttons['remove-consumer'].disabled = !selectedConsumer; buttons['issue-key'].disabled = !selectedConsumer || !selectedConsumer.enabled; buttons['rotate-key'].disabled = !selectedKey || Boolean(selectedKey.revokedAt); buttons['revoke-key'].disabled = !selectedKey || Boolean(selectedKey.revokedAt); buttons['edit-permission'].disabled = !selectedPermission; buttons['remove-permission'].disabled = !selectedPermission; }
  async function load() { const [consumers, permissions] = await Promise.all([api.get('/consumers'), api.get('/permissions')]); selectedConsumer = null; selectedKey = null; selectedPermission = null; refreshButtons(); if (consumersGrid) consumersGrid.update(consumers); else consumersGrid = createGrid({ name: 'consumers_grid', box: '#consumers-grid', items: consumers, columns: [{ field: 'name', text: 'Short name', size: '30%' }, { field: 'displayName', text: 'Display name', size: '42%' }, { field: 'enabled', text: 'Status', size: '22%', render: (record) => statusHTML(record.enabled ? 'active' : 'disabled') }], onSelect: async (record) => { selectedConsumer = record; selectedKey = null; refreshButtons(); await loadKeys(); } }); if (permissionsGrid) permissionsGrid.update(permissions); else permissionsGrid = createGrid({ name: 'permissions_grid', box: '#permissions-grid', items: permissions, columns: [{ field: 'name', text: 'Access', size: '55%', render: (record) => friendlyPermissionName(record.name) }, { field: 'description', text: 'Notes', size: '45%' }], onSelect: (record) => { selectedPermission = record; refreshButtons(); } }); await loadKeys(); }
  async function loadKeys() { selectedKey = null; refreshButtons(); const keys = selectedConsumer ? await api.get(`/consumers/${selectedConsumer.id}/keys`) : []; if (keysGrid) keysGrid.update(keys); else keysGrid = createGrid({ name: 'keys_grid', box: '#keys-grid', items: keys, columns: [{ field: 'name', text: 'Label', size: '30%' }, { field: 'maskedPrefix', text: 'Key prefix', size: '24%' }, { field: 'expiresAt', text: 'Expires', size: '26%', render: (record) => formatDate(record.expiresAt) }, { field: 'revokedAt', text: 'State', size: '20%', render: (record) => statusHTML(record.revokedAt ? 'revoked' : 'active') }], onSelect: (record) => { selectedKey = record; refreshButtons(); } }); }
  async function permissionChoices() { return (await api.get('/permissions')).map(permissionChoice); }
  async function createConsumer() { const permissions = await permissionChoices(); const record = await showForm({ title: 'Add API client', fields: [{ field: 'name', type: 'text', required: true, html: { label: 'Short name', text: '<small class="field-help">A simple lowercase name, such as mobile-app.</small>' } }, { field: 'displayName', type: 'text', required: true, html: { label: 'Display name' } }, { field: 'permissions', type: 'enum', options: { items: permissions }, html: { label: 'Allowed access' } }], record: { permissions: [] }, validate: (item) => !serviceName(item.name) ? ['Use a lowercase short name, such as mobile-app.'] : !required(item.displayName) ? ['Display name is required.'] : [] }); if (!record) return; record.permissions = selectedValues(record.permissions); await api.post('/consumers', record); notify('API client added.', 'success'); await load(); }
  async function editConsumer() { if (!selectedConsumer) return; const permissions = await permissionChoices(); const record = await showForm({ title: `Edit ${selectedConsumer.displayName}`, fields: [{ field: 'displayName', type: 'text', required: true, html: { label: 'Display name' } }, { field: 'enabled', type: 'list', required: true, options: { items: [choice('true', 'Active'), choice('false', 'Disabled')] }, html: { label: 'Status' } }, { field: 'permissions', type: 'enum', options: { items: permissions }, html: { label: 'Allowed access' } }], record: { displayName: selectedConsumer.displayName, enabled: choice(String(selectedConsumer.enabled), selectedConsumer.enabled ? 'Active' : 'Disabled'), permissions: permissions.filter((item) => (selectedConsumer.permissions || []).includes(item.id)) }, validate: (item) => required(item.displayName) ? [] : ['Display name is required.'] }); if (!record) return; try { await api.patch(`/consumers/${selectedConsumer.id}`, { displayName: record.displayName, enabled: selectedValue(record.enabled) === 'true', permissions: selectedValues(record.permissions), expectedVersion: selectedConsumer.rowVersion }); notify('API client updated.', 'success'); await load(); } catch (error) { notify(error.message, 'error'); } }
  async function removeConsumer() { if (!selectedConsumer) return; if (!await confirmAction(`Remove ${selectedConsumer.displayName}? Clients with key history must be disabled instead.`)) return; try { await api.delete(`/consumers/${selectedConsumer.id}`); notify('API client removed.', 'success'); await load(); } catch (error) { notify(error.status === 409 ? 'This client has key history. Revoke its keys and set the client to Disabled instead.' : error.message, 'error', 6000); } }
  async function editPermission() { if (!selectedPermission) return; const record = await showForm({ title: `Edit ${friendlyPermissionName(selectedPermission.name)}`, fields: [{ field: 'description', type: 'textarea', html: { label: 'Notes' } }], record: { description: selectedPermission.description || '' } }); if (!record) return; try { await api.patch(`/permissions/${selectedPermission.id}`, { description: record.description || '' }); notify('Access rule updated.', 'success'); await load(); } catch (error) { notify(error.message, 'error'); } }
  async function removePermission() { if (!selectedPermission) return; if (!await confirmAction(`Remove ${friendlyPermissionName(selectedPermission.name)}?`)) return; try { await api.delete(`/permissions/${selectedPermission.id}`); notify('Access rule removed.', 'success'); await load(); } catch (error) { notify(error.status === 409 ? 'This access rule is still assigned to a client or listener. Remove those assignments first.' : error.message, 'error', 6000); } }
  async function issueKey() { if (!selectedConsumer) { notify('Select an API client first.', 'error'); return; } const record = await showForm({ title: `Create key for ${selectedConsumer.displayName || selectedConsumer.name}`, fields: [{ field: 'name', type: 'text', required: true, html: { label: 'Key label', text: '<small class="field-help">Use a memorable label, such as Production mobile app.</small>' } }, { field: 'expiresAt', type: 'datetime', html: { label: 'Expires (optional)' } }], validate: (item) => !required(item.name) ? ['Add a label for this key.'] : item.expiresAt && optionalISOString(item.expiresAt) === null ? ['Choose a valid expiration date and time.'] : [] }); if (!record) return; const expiration = optionalISOString(record.expiresAt); record.permissions = selectedConsumer.permissions || []; if (expiration) record.expiresAt = expiration; else delete record.expiresAt; try { const issued = await api.post(`/consumers/${selectedConsumer.id}/keys`, record); showSecretOnce(issued.key); issued.key = ''; notify('Key created. Copy it before closing the dialog.', 'success'); await loadKeys(); } catch (error) { notify(error.message, 'error'); } }
  async function rotateKey() { if (!selectedKey) { notify('Select a key first.', 'error'); return; } if (!await confirmAction('Rotate this key and revoke the previous credential?')) return; const issued = await api.post(`/keys/${selectedKey.id}/rotate`, {}); showSecretOnce(issued.key); issued.key = ''; await loadKeys(); }
  async function revokeKey() { if (!selectedKey) { notify('Select a key first.', 'error'); return; } if (!await confirmAction('Revoke this API key immediately?')) return; await api.post(`/keys/${selectedKey.id}/revoke`, {}); notify('Key revoked.', 'success'); await loadKeys(); }
  try { await load(); } catch (error) { notify(error.message, 'error'); }
  return () => { consumersGrid?.destroy(); keysGrid?.destroy(); permissionsGrid?.destroy(); };
}
