import { api } from '../api-client.js';
import { mountView } from '../components/view-shell.js';
import { createGrid } from '../components/data-grid.js';
import { showForm } from '../components/edit-form.js';
import { confirmAction } from '../components/confirm-dialog.js';
import { notify } from '../components/notification.js';
import { permissionName, portNumber, routeRegex } from '../utils/validation.js';
import { statusHTML } from '../utils/formatting.js';
import { choice, selectedValue, selectedValues } from '../utils/form-values.js';
import { friendlyPermissionName, permissionChoice } from '../utils/permissions.js';
import { createPermissionRule } from '../components/permission-form.js';
import { showListenerDetails } from '../components/listener-details-dialog.js';

const HTTP_METHODS = ['GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'].map((value) => choice(value));
const CONTENT_TYPES = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data', 'application/octet-stream', 'text/plain'].map((value) => choice(value));
const UNPROTECTED_ROUTE_HELP = '<small class="field-help">Optional RE2 regex matched against the URL path. Example: <code>^/(swagger|docs)(/.*)?$|\\.(js|css|ya?ml|jpe?g|png|svg)$</code>. Only GET and HEAD bypass API-key checks.</small>';

export async function render() {
  let portsGrid; let listenersGrid; let selectedPort; let selectedListener; let listenerItems = [];
  const shell = mountView('Ports & listeners', 'Allocate the environment port pool and manage listener lifecycle.', [{ label: 'Allocate listener', primary: true, onClick: allocate }, { label: 'Add access rule', onClick: () => createPermissionRule() }], 'ports');
  shell.content.innerHTML = '<div class="split-layout"><section class="panel"><h2>Port inventory</h2><div class="view-actions"><button id="release-port" type="button">Release</button><button id="block-port" type="button" class="danger-button">Block</button></div><div id="ports-grid" class="grid-host"></div></section><section class="panel"><h2>Listeners</h2><div class="view-actions"><button id="listener-details" type="button" disabled>Connection details</button><button data-status="active" type="button">Activate</button><button data-status="draining" type="button">Drain</button><button data-status="disabled" type="button" class="danger-button">Disable</button><button id="edit-policies" type="button">Policies</button></div><div id="listeners-grid" class="grid-host"></div></section></div>';
  const detailsButton = document.querySelector('#listener-details');
  document.querySelector('#release-port').addEventListener('click', () => changePort('available')); document.querySelector('#block-port').addEventListener('click', () => changePort('blocked')); detailsButton.addEventListener('click', showConnectionDetails); document.querySelector('#edit-policies').addEventListener('click', editPolicies); for (const button of document.querySelectorAll('[data-status]')) button.addEventListener('click', () => changeListener(button.dataset.status));
  async function load() { const [ports, listeners] = await Promise.all([api.get('/ports'), api.get('/listeners')]); listenerItems = listeners; selectedPort = null; selectedListener = null; detailsButton.disabled = true; if (portsGrid) portsGrid.update(ports); else portsGrid = createGrid({ name: 'ports_grid', box: '#ports-grid', items: ports, columns: [{ field: 'listenPort', text: 'Port', size: '25%' }, { field: 'status', text: 'Status', size: '35%', render: (record) => statusHTML(record.status) }, { field: 'listenerId', text: 'Listener', size: '40%' }], onSelect: (record) => { selectedPort = record; } }); if (listenersGrid) listenersGrid.update(listeners); else listenersGrid = createGrid({ name: 'listeners_grid', box: '#listeners-grid', items: listeners, columns: [{ field: 'listenPort', text: 'Port', size: '18%' }, { field: 'requiredPermission', text: 'Required access', size: '35%', render: (record) => friendlyPermissionName(record.requiredPermission) }, { field: 'status', text: 'Status', size: '22%', render: (record) => statusHTML(record.status) }, { field: 'rowVersion', text: 'Version', size: '15%' }], onSelect: (record) => { selectedListener = record; detailsButton.disabled = false; } }); }
  async function showConnectionDetails() {
    if (!selectedListener) { notify('Select a listener first.', 'error'); return; }
    try {
      const services = await api.get('/services');
      let service = null; let version = null;
      for (const candidate of services) {
        const versions = await api.get(`/services/${encodeURIComponent(candidate.name)}/versions`);
        version = versions.find((item) => item.id === selectedListener.serviceVersionId);
        if (version) { service = candidate; break; }
      }
      const upstreams = await api.get(`/service-versions/${encodeURIComponent(selectedListener.serviceVersionId)}/upstreams`);
      showListenerDetails({ listener: selectedListener, service, version, upstreams: upstreams.filter((item) => item.enabled !== false) });
    } catch (error) { notify(error.message, 'error'); }
  }
  async function allocate() {
    const [services, ports, catalog] = await Promise.all([api.get('/services'), api.get('/ports'), api.get('/permissions')]);
    const versionSets = await Promise.all(services.map(async (service) => ({ service, versions: await api.get(`/services/${encodeURIComponent(service.name)}/versions`) })));
    const serviceVersions = versionSets.flatMap(({ service, versions }) => versions.map((version) => choice(`${service.name}/${version.version}`, `${service.displayName || service.name} / ${version.version}`)));
    const availablePorts = ports.filter((port) => port.status === 'available').map((port) => choice(port.listenPort));
    const permissions = catalog.slice();
    if (permissions.length === 0) { const first = versionSets.find((entry) => entry.versions.length > 0); const suggestedServiceVersion = first ? `${first.service.name}/${first.versions[0].version}` : ''; notify('Add the first access rule before allocating a listener.', 'info', 5000); const created = await createPermissionRule({ suggestedServiceVersion, title: 'Set up access' }); if (!created) return; permissions.push(created); }
    const permissionItems = permissions.map(permissionChoice);
    const record = await showForm({ title: 'Allocate listener', fields: [{ field: 'serviceVersionChoice', type: 'list', required: true, options: { items: serviceVersions }, html: { label: 'Which API?' } }, { field: 'preferredPort', type: 'list', options: { items: availablePorts }, html: { label: 'Preferred port (optional)' } }, { field: 'requiredPermission', type: 'list', required: true, options: { items: permissionItems }, html: { label: 'Required access' } }, { field: 'allowedMethods', type: 'enum', options: { items: HTTP_METHODS }, html: { label: 'Allowed request types' } }, { field: 'allowedContentTypes', type: 'enum', options: { items: CONTENT_TYPES }, html: { label: 'Accepted content' } }, { field: 'unprotectedRouteRegex', type: 'textarea', html: { label: 'Unprotected route regex', text: UNPROTECTED_ROUTE_HELP } }, { field: 'rateLimitPerSecond', type: 'int', html: { label: 'Requests per second (0 disables)' } }, { field: 'rateLimitBurst', type: 'int', html: { label: 'Short traffic burst' } }, { field: 'quotaRequestsPerMinute', type: 'int', html: { label: 'Requests per client each minute' } }, { field: 'circuitFailureThreshold', type: 'int', html: { label: 'Failures before pausing traffic' } }, { field: 'circuitOpenMs', type: 'int', html: { label: 'Pause duration (ms)' } }], record: { allowedMethods: [choice('GET'), choice('HEAD'), choice('POST')], allowedContentTypes: [choice('application/json')], unprotectedRouteRegex: '', rateLimitPerSecond: 0, rateLimitBurst: 0, quotaRequestsPerMinute: 0, circuitFailureThreshold: 5, circuitOpenMs: 30000 }, validate: (item) => !selectedValue(item.serviceVersionChoice) ? ['Choose an API.'] : !permissionName(selectedValue(item.requiredPermission)) ? ['Choose the required access.'] : selectedValue(item.preferredPort) && !portNumber(selectedValue(item.preferredPort)) ? ['Preferred port is invalid.'] : selectedValues(item.allowedMethods).length === 0 ? ['Choose at least one request type.'] : selectedValues(item.allowedContentTypes).length === 0 ? ['Choose at least one accepted content type.'] : !routeRegex(item.unprotectedRouteRegex) ? ['Enter a valid route regex of at most 2048 characters.'] : [item.rateLimitPerSecond, item.rateLimitBurst, item.quotaRequestsPerMinute].some((value) => Number(value) < 0) ? ['Traffic limits cannot be negative.'] : Number(item.circuitFailureThreshold) < 1 || Number(item.circuitOpenMs) < 1000 ? ['Failure protection values are invalid.'] : [] });
    if (!record) return;
    [record.service, record.serviceVersion] = String(selectedValue(record.serviceVersionChoice)).split('/', 2); delete record.serviceVersionChoice;
    record.requiredPermission = String(selectedValue(record.requiredPermission));
    record.allowedMethods = selectedValues(record.allowedMethods); record.allowedContentTypes = selectedValues(record.allowedContentTypes);
    const preferredPort = selectedValue(record.preferredPort); if (preferredPort) record.preferredPort = Number(preferredPort); else delete record.preferredPort;
    await api.post('/listeners/allocate-port', record); notify('Listener allocated. Publish a configuration before distributing its address.', 'success', 6000); await load();
  }
  async function changePort(status) { if (!selectedPort) { notify('Select a port first.', 'error'); return; } const attached = selectedPort.listenerId ? listenerItems.find((listener) => listener.listenerId === selectedPort.listenerId) : null; const message = status === 'blocked' && attached && attached.status !== 'disabled' ? `Block port ${selectedPort.listenPort}? Its attached listener will be disabled immediately.` : `Change port ${selectedPort.listenPort} to ${status}?`; if (!await confirmAction(message)) return; try { await api.patch(`/ports/${selectedPort.listenPort}`, { status }); notify(status === 'blocked' && attached ? 'Port blocked and attached listener disabled.' : 'Port updated.', 'success'); await load(); } catch (error) { notify(error.message, 'error'); } }
  async function changeListener(status) { if (!selectedListener) { notify('Select a listener first.', 'error'); return; } if (!await confirmAction(`Change listener ${selectedListener.listenerId} to ${status}?`)) return; await api.patch(`/listeners/${selectedListener.listenerId}`, { status, expectedVersion: selectedListener.rowVersion }); notify('Listener updated. Publish a configuration to apply this change to the gateways.', 'success', 6000); await load(); }
  async function editPolicies() { if (!selectedListener) { notify('Select a listener first.', 'error'); return; } const record = await showForm({ title: 'Listener policies', fields: [{ field: 'unprotectedRouteRegex', type: 'textarea', html: { label: 'Unprotected route regex', text: UNPROTECTED_ROUTE_HELP } }, { field: 'rateLimitPerSecond', type: 'int', html: { label: 'Requests per second' } }, { field: 'rateLimitBurst', type: 'int', html: { label: 'Rate burst' } }, { field: 'quotaRequestsPerMinute', type: 'int', html: { label: 'Consumer quota per minute' } }, { field: 'circuitFailureThreshold', type: 'int', html: { label: 'Circuit threshold (0 disables)' } }, { field: 'circuitOpenMs', type: 'int', html: { label: 'Circuit open duration (ms)' } }], record: { unprotectedRouteRegex: selectedListener.unprotectedRouteRegex || '', rateLimitPerSecond: selectedListener.rateLimitPerSecond, rateLimitBurst: selectedListener.rateLimitBurst, quotaRequestsPerMinute: selectedListener.quotaRequestsPerMinute, circuitFailureThreshold: selectedListener.circuitFailureThreshold, circuitOpenMs: selectedListener.circuitOpenMs }, validate: (item) => !routeRegex(item.unprotectedRouteRegex) ? ['Enter a valid route regex of at most 2048 characters.'] : [item.rateLimitPerSecond, item.rateLimitBurst, item.quotaRequestsPerMinute, item.circuitFailureThreshold].some((value) => Number(value) < 0) || Number(item.circuitOpenMs) < 1000 ? ['Policy values are invalid.'] : [] }); if (!record) return; record.expectedVersion = selectedListener.rowVersion; await api.patch(`/listeners/${selectedListener.listenerId}/policies`, record); notify('Listener policies updated. Activate a new configuration to publish them.', 'success'); await load(); }
  try { await load(); } catch (error) { notify(error.message, 'error'); }
  return () => { portsGrid?.destroy(); listenersGrid?.destroy(); };
}
