import { api } from '../api-client.js';
import { mountView } from '../components/view-shell.js';
import { createGrid } from '../components/data-grid.js';
import { showForm } from '../components/edit-form.js';
import { notify } from '../components/notification.js';
import { serviceName, versionName, literalIP, portNumber, required } from '../utils/validation.js';
import { formatBytes } from '../utils/formatting.js';
import { choice, selectedValue } from '../utils/form-values.js';

export async function render() {
  let selectedService = null; let selectedVersion = null; let selectedUpstream = null; let servicesGrid; let versionsGrid; let upstreamsGrid;
  const shell = mountView('Services', 'Register services, versions, and literal-IP upstreams.', [{ label: 'New service', primary: true, onClick: createService }], 'services');
  shell.content.innerHTML = '<div class="split-layout"><section class="panel"><h2>Services</h2><div class="view-actions"><button id="edit-service" type="button">Edit</button></div><div id="services-grid" class="grid-host"></div></section><div class="stack"><section class="panel"><h2>Versions</h2><div class="view-actions"><button id="add-version" type="button">Add version</button><button id="edit-version" type="button">Edit</button></div><div id="versions-grid" class="grid-host compact"></div></section><section class="panel"><h2>Upstreams</h2><div class="view-actions"><button id="add-upstream" type="button">Add upstream</button><button id="edit-upstream" type="button">Edit</button></div><div id="upstreams-grid" class="grid-host compact"></div></section></div></div>';
  document.querySelector('#edit-service').addEventListener('click', editService); document.querySelector('#add-version').addEventListener('click', createVersion); document.querySelector('#edit-version').addEventListener('click', editVersion); document.querySelector('#add-upstream').addEventListener('click', createUpstream); document.querySelector('#edit-upstream').addEventListener('click', editUpstream);
  async function loadServices() { const items = await api.get('/services'); if (servicesGrid) servicesGrid.update(items); else servicesGrid = createGrid({ name: 'services_grid', box: '#services-grid', items, columns: [{ field: 'name', text: 'Name', size: '25%' }, { field: 'displayName', text: 'Display name', size: '35%' }, { field: 'owner', text: 'Owner', size: '25%' }, { field: 'enabled', text: 'Enabled', size: '15%' }], onSelect: async (record) => { selectedService = record; selectedVersion = null; await loadVersions(); } }); }
  async function loadVersions() { selectedVersion = null; selectedUpstream = null; const items = selectedService ? await api.get(`/services/${encodeURIComponent(selectedService.name)}/versions`) : []; versionsGrid?.destroy(); versionsGrid = createGrid({ name: 'versions_grid', box: '#versions-grid', items, columns: [{ field: 'version', text: 'Version', size: '22%' }, { field: 'requestTimeoutMs', text: 'Timeout ms', size: '24%' }, { field: 'maxRequestBytes', text: 'Max body', size: '28%', render: (record) => formatBytes(record.maxRequestBytes) }, { field: 'enabled', text: 'Enabled', size: '20%' }], onSelect: async (record) => { selectedVersion = record; await loadUpstreams(); } }); await loadUpstreams(); }
  async function loadUpstreams() { selectedUpstream = null; const items = selectedVersion ? await api.get(`/service-versions/${selectedVersion.id}/upstreams`) : []; upstreamsGrid?.destroy(); upstreamsGrid = createGrid({ name: 'upstreams_grid', box: '#upstreams-grid', items, columns: [{ field: 'scheme', text: 'Protocol', size: '14%' }, { field: 'address', text: 'Address', size: '27%' }, { field: 'port', text: 'Port', size: '14%' }, { field: 'weight', text: 'Weight', size: '14%' }, { field: 'healthCheckPath', text: 'Health path', size: '31%' }], onSelect: (record) => { selectedUpstream = record; } }); }
  async function createService() { const record = await showForm({ title: 'Register service', fields: [{ field: 'name', type: 'text', required: true, html: { label: 'Name' } }, { field: 'displayName', type: 'text', required: true, html: { label: 'Display name' } }, { field: 'owner', type: 'text', html: { label: 'Owner' } }], validate: (item) => !serviceName(item.name) ? ['Use a lowercase service name such as rtp-service.'] : !required(item.displayName) ? ['Display name is required.'] : [] }); if (!record) return; await api.post('/services', record); notify('Service registered.', 'success'); await loadServices(); }
  async function editService() { if (!selectedService) { notify('Select a service first.', 'error'); return; } const record = await showForm({ title: `Edit ${selectedService.name}`, fields: [{ field: 'displayName', type: 'text', required: true, html: { label: 'Display name' } }, { field: 'owner', type: 'text', html: { label: 'Owner' } }, { field: 'enabled', type: 'list', required: true, options: { items: [choice('true', 'Enabled'), choice('false', 'Disabled')] }, html: { label: 'Status' } }], record: { displayName: selectedService.displayName, owner: selectedService.owner, enabled: choice(String(selectedService.enabled), selectedService.enabled ? 'Enabled' : 'Disabled') }, validate: (item) => required(item.displayName) ? [] : ['Display name is required.'] }); if (!record) return; await api.patch(`/services/${encodeURIComponent(selectedService.name)}`, { displayName: record.displayName, owner: record.owner || '', enabled: selectedValue(record.enabled) === 'true', expectedVersion: selectedService.rowVersion }); notify('Service updated.', 'success'); selectedService = null; await loadServices(); await loadVersions(); }
  async function createVersion() { if (!selectedService) { notify('Select a service first.', 'error'); return; } const record = await showForm({ title: `Add version to ${selectedService.name}`, fields: [{ field: 'version', type: 'text', required: true, html: { label: 'Version', text: '<small class="field-help">Use 1–128 characters without spaces, such as stable, 2026.08, or v1.</small>' } }, { field: 'healthCheckPath', type: 'text', html: { label: 'Health path' } }, { field: 'requestTimeoutMs', type: 'int', html: { label: 'Timeout (ms)' } }, { field: 'maxRequestBytes', type: 'int', html: { label: 'Max request bytes' } }], record: { healthCheckPath: '/health', requestTimeoutMs: 30000, maxRequestBytes: 2097152 }, validate: (item) => versionName(item.version) ? [] : ['Version must contain 1–128 characters and no spaces.'] }); if (!record) return; await api.post(`/services/${encodeURIComponent(selectedService.name)}/versions`, record); notify('Version created.', 'success'); await loadVersions(); }
  async function editVersion() { if (!selectedVersion) { notify('Select a version first.', 'error'); return; } const record = await showForm({ title: `Edit version ${selectedVersion.version}`, fields: [{ field: 'version', type: 'text', required: true, html: { label: 'Version' } }, { field: 'healthCheckPath', type: 'text', required: true, html: { label: 'Health path' } }, { field: 'requestTimeoutMs', type: 'int', required: true, html: { label: 'Timeout (ms)' } }, { field: 'maxRequestBytes', type: 'int', required: true, html: { label: 'Max request bytes' } }, { field: 'enabled', type: 'list', required: true, options: { items: [choice('true', 'Enabled'), choice('false', 'Disabled')] }, html: { label: 'Status' } }], record: { ...selectedVersion, enabled: choice(String(selectedVersion.enabled), selectedVersion.enabled ? 'Enabled' : 'Disabled') }, validate: (item) => !versionName(item.version) ? ['Version must contain 1–128 characters and no spaces.'] : !String(item.healthCheckPath || '').startsWith('/') ? ['Health path must start with /.'] : Number(item.requestTimeoutMs) < 1 || Number(item.maxRequestBytes) < 1 ? ['Timeout and request size must be positive.'] : [] }); if (!record) return; await api.patch(`/service-versions/${selectedVersion.id}`, { version: record.version, healthCheckPath: record.healthCheckPath, requestTimeoutMs: Number(record.requestTimeoutMs), maxRequestBytes: Number(record.maxRequestBytes), enabled: selectedValue(record.enabled) === 'true', expectedVersion: selectedVersion.rowVersion }); notify('Version updated.', 'success'); await loadVersions(); }
  async function createUpstream() { if (!selectedVersion) { notify('Select a service version first.', 'error'); return; } const record = await showForm({ title: `Add upstream to ${selectedVersion.version}`, fields: [{ field: 'scheme', type: 'list', required: true, html: { label: 'Protocol' }, options: { items: [{ id: 'https', text: 'HTTPS' }, { id: 'http', text: 'HTTP' }] } }, { field: 'address', type: 'text', required: true, html: { label: 'Literal IP address' } }, { field: 'port', type: 'int', required: true, html: { label: 'Port' } }, { field: 'weight', type: 'int', html: { label: 'Weight' } }, { field: 'healthCheckPath', type: 'text', html: { label: 'Health path' } }], record: { scheme: { id: 'https', text: 'HTTPS' }, weight: 100, healthCheckPath: '/health' }, validate: (item) => !['http', 'https'].includes(item.scheme?.id || item.scheme) ? ['Choose HTTP or HTTPS.'] : !literalIP(item.address) ? ['A literal IP address is required.'] : !portNumber(item.port) ? ['Port must be between 1 and 65535.'] : [] }); if (!record) return; record.scheme = record.scheme?.id || record.scheme; await api.post(`/service-versions/${selectedVersion.id}/upstreams`, record); notify('Upstream added.', 'success'); await loadUpstreams(); }
  async function editUpstream() { if (!selectedVersion || !selectedUpstream) { notify('Select an upstream first.', 'error'); return; } const record = await showForm({ title: `Edit ${selectedUpstream.address}:${selectedUpstream.port}`, fields: [{ field: 'scheme', type: 'list', required: true, options: { items: [choice('https', 'HTTPS'), choice('http', 'HTTP')] }, html: { label: 'Protocol' } }, { field: 'address', type: 'text', required: true, html: { label: 'Literal IP address' } }, { field: 'port', type: 'int', required: true, html: { label: 'Port' } }, { field: 'weight', type: 'int', required: true, html: { label: 'Weight' } }, { field: 'healthCheckPath', type: 'text', required: true, html: { label: 'Health path' } }, { field: 'enabled', type: 'list', required: true, options: { items: [choice('true', 'Enabled'), choice('false', 'Disabled')] }, html: { label: 'Status' } }], record: { ...selectedUpstream, scheme: choice(selectedUpstream.scheme, selectedUpstream.scheme.toUpperCase()), enabled: choice(String(selectedUpstream.enabled), selectedUpstream.enabled ? 'Enabled' : 'Disabled') }, validate: (item) => !['http', 'https'].includes(selectedValue(item.scheme)) ? ['Choose HTTP or HTTPS.'] : !literalIP(item.address) ? ['A literal IP address is required.'] : !portNumber(item.port) ? ['Port must be between 1 and 65535.'] : Number(item.weight) < 1 ? ['Weight must be positive.'] : !String(item.healthCheckPath || '').startsWith('/') ? ['Health path must start with /.'] : [] }); if (!record) return; await api.patch(`/service-versions/${selectedVersion.id}/upstreams/${selectedUpstream.id}`, { scheme: selectedValue(record.scheme), address: record.address, port: Number(record.port), weight: Number(record.weight), healthCheckPath: record.healthCheckPath, enabled: selectedValue(record.enabled) === 'true', expectedVersion: selectedUpstream.rowVersion }); notify('Upstream updated.', 'success'); await loadUpstreams(); }
  try { await loadServices(); await loadVersions(); } catch (error) { notify(error.message, 'error'); }
  return () => { servicesGrid?.destroy(); versionsGrid?.destroy(); upstreamsGrid?.destroy(); };
}
